export const REQUEST_SEARCH_RESULTS = "REQUEST_SEARCH_RESULTS";
export const REQUEST_SEARCH_RESULTS_SUCCESS = "REQUEST_SEARCH_RESULTS_SUCCESS";
export const REQUEST_SEARCH_RESULTS_ERROR = "REQUEST_SEARCH_RESULTS_ERROR";
